DROP TABLE IF EXISTS singer;
CREATE TABLE IF NOT EXISTS singer (ID INTEGER NOT NULL AUTO_INCREMENT, NAME VARCHAR (60) NOT NULL);

INSERT INTO singer (NAME) VALUE ('Vasil');
INSERT INTO singer (NAME) VALUE ('Rita');